otp: Autospec creation for update from version 25.2 to version 25.3
Alexandre Fruchaud (1):
      fix typo

Björn Gustavsson (14):
      Fix failed assertion in debug build
      Update primary bootstrap
      GC: Support heap needs of more than 2 GiB
      BEAM disassembler: Correct printout of W operands
      non-JIT BEAM: Avoid redundant GC in binary syntax
      Eliminate compiler crash in binary construction
      Documentation: Fix subject/verb clash
      AArch64 JIT: Fix crash in bxor/2
      Exit process immediately when the max heap size is exceeded
      Exit process immediately when the max heap size is exceeded
      Exit process immediately when the max heap size is exceeded
      Eliminate "mutable variables"
      Eliminate "mutable variables"
      lists_to_integer() & friends: Don't crash for overlong lists

Dan Gudmundsson (13):
      Fix version test
      Refactor, remove client set
      Unlink port_command to avoid EXIT msgs
      ssl: dtls let new accept process handle new connections
      Limits NSIS versions
      Rename macros
      Use OTP version as product version in installer
      Make copyright year dynamic
      Win installer version fix
      mnesia: Improve dirty writes consistency
      mnesia: Improve docs
      mnesia: Swap slave with peer
      Fix sticky sync locks

Erlang/OTP (15):
      Update copyright year
      Prepare release
      Updated OTP version
      Update copyright year
      Prepare release
      Updated OTP version
      Update copyright year
      Prepare release
      Updated OTP version
      Update copyright year
      Prepare release
      Updated OTP version
      Update copyright year
      Prepare release
      Updated OTP version

Gerard Tabone (1):
      Removed unnecessary <em> tags

Henrik Nord (1):
      Prepare for development

Ingela Anderton Andin (5):
      ssl: Refactor to avoid confusion of what is the API
      ssl: Improve interop test
      ssl: Maximize compatibility
      ssl: Adjust assert of middlebox change_cipher_spec for better interop
      public_key: Move decode of CRLDistributionPoints extension

Jakub Witczak (4):
      ssh: accept PKCS#8 host key
      ssh: fix kexinit error generation
      ssh: reduce log length
      inets: fix httpd and folder URI alias

John Högberg (20):
      erts: Silently convert FILETIME of -1 to 0 on Windows
      erts: Cap file times to {{9999,12,31},{23,59,59}}
      dialyzer_dataflow: Fix bug in bind_checked_inf/4
      dialyzer: Rename t_is_none_or_unit/1 to t_is_impossible/1
      erl_error: Fix parameter order bug
      system: Clarify documentation for enabling 'maybe'
      beam_bounds: Don't choke on division by zero
      v3_kernel: Mark #k_goto{} arguments as used
      erts: Fix erts_poll_get_selected_events on some platforms
      erts: Port 508b6e55b61f34fd768833510a30e8e72bbc4c6e to ARM
      jit: Fix float negation on x64
      erts: Float negation cannot fail
      jit: Remove an eyesore
      jit: Issue ISBs on all schedulers when modifying code
      jit: Refactor breakpoints
      jit: Clear instruction cache ourselves
      erts: Add `+JPperf no_fp` option to suppress frame pointers
      erts: Fix out-of-bounds copy in load_nif_1st_finisher
      make: Fix configure test for ISB/cache control on ARM
      Update configure scripts

Julian Doherty (1):
      erts: Fix ets:insert with list into bag being reversed

Kiko Fernandez-Reyes (29):
      public_key: date sliding window validation function
      public_key: add typespecs to pubkey_cert
      public_key: add types/delete redundant code pkits_SUITE
      public_key: update tests to not depend on year
      xmerl: replace calls to size/1 by tuple_size/1
      inets: replace size/1 by XXX_size/1
      eunit: replace call size/1 by XXX_size/1
      stdlib: remove unnecessary undefined from records
      public_key: replace size/1 by XXX_size/1
      snmp: replace size/1 by XXX_size/1
      mnesia: replace size/1 by XXX_size/1
      ssh: replace size/1 by XXX_size/1
      dialyzer: replace size/1 by XXX_size/1
      ssh: fix indentation issues
      inets: replace size/1 by xxx_size/1
      megaco: replace size/1 by xxx_size/1
      mnesia: replace size/1 by xxx_size/1
      ssh: replace size/1 by xxx_size/1
      ssl: replace size/1 by xxx_size/1
      ftp: replace size/1 by XXX_size/1
      ftp: remove redundant is_{tuple/binary}/1
      tftp: replace size/1 by xxx_size/1
      snmp: replace size/1 by xxx_size/1
      xmerl: replace size/1 by xxx_size/1
      snmp: replace size by xxx_size
      ftp: fix forgotten guard
      inets: update function heads and types
      inets: refactor code to improve readability
      inets: refactor code for consistency

Luke Bakken (1):
      Update various file and installer properties

Maria Scott (1):
      Update list of map functions consuming iterators

Marko Minđek (1):
      named_fun_expr annotate bindings fix

Matthew Smith (1):
      kernel: os_SUITE: fix close_stdin test

Maxim Fedorov (2):
      [erts] report writable binaries as off-heap binaries
      Do not emit "unexpected" message on shutdown

Micael Karlberg (3):
      [kernel|test|gen-tcp-misc] Tweaked send_timeout_resume tc
      [kernel|test] Cleanup
      [kernel] Minor adjustments to the Solaris analyzis

Radek Szymczyszyn (1):
      Call erlang:error/2 with the actual args in erl_anno:anno_info/2,3

Rickard Green (7):
      Update configure scripts
      [erts] Support for truly asynchronous distributed signaling
      [crypto] Fix configuration of runtime library path
      Update configure scripts
      Add info about async_dist in reference manual
      [erts] Ensure cleanup of alias table on alias destruction
      Update patch merge version

Sverker Eriksson (20):
      common_test: Rename undocumented macro CT_PEER/3 -> CT_PEER_REL
      test_server: Introduce os env TEST_SERVER_RELEASE_ROOT
      pg_SUITE: Test communication with old OTP release
      erts: Fix race receiving fragmented msg on terminating connection
      erts: Save otp_src directory if z_SUITE:core_files fails
      erts: Fix etp-command in "make local_setup"
      kerne: Fix os_SUITE:init_per_suite
      erts: Fix bug in erts_io_notify_port_task_executed
      kernel: Accept ver5 distribution connection setup
      erl_interface: Accept ver5 distribution connection setup
      jinterface: Accept ver5 distribution connection setup
      erts: Fix cerl options -core and -gdb
      stdlib: Improve ets documentation about insert/lookup times
      erts: Refactor rename a shadowing local variable
      erts: Don't allocate a new heap that we know will not suffice
      erts: Avoid incorrect exception trace of terminating processes
      erts: Make sure process reaching max_heap_size exits pronto
      erts: Refactor minor_collection with need += S_RESERVED
      erts: Fix missing increment of binary overhead
      erts: Make sure process reaching max_heap_size exits pronto (AGAIN)

Tomas Abrahamsson (1):
      Fix a doc link to flamegraphs on the BeamAsm page

Tyler J. Stachecki (1):
      lib/crypto: autoconf: Add missing ',' in an AC_IF

Zeyu Zhang (1):
      avoid crash when tracer = erts_tracer_nil

jdamanalo (1):
      Close cpu_sup and memsup port on terminate